name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-job:
    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
      - name: Repo'yu checkout et
        uses: actions/checkout@v3

      - name: Çalışma dizinini kontrol et
        run: |
          pwd
          ls -la
          ls -la yemek-tarifi

      - name: Deploy işlemi
        run: |
          echo "Buraya deploy komutlarını ekle"
          # Örnek:
          # scp -r yemek-tarifi/* user@sunucu:/var/www/html/
