name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-job:
    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
      - name: Repo'yu checkout et
        uses: actions/checkout@v3

      - name: Node.js kurulumu (örnek)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Bağımlılıkları yükle
        run: npm install

      - name: Build işlemi
        run: npm run build

      - name: Deploy işlemi
        run: echo "Deploy komutları buraya gelecek"

     
