
name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22                       # <-- Bu satırı buraya ekle
          script: |
            docker pull ssevginurr/yemek-tarifi:latest
            docker stop yemek-tarifi || true
            docker rm yemek-tarifi || true
            docker run -d --name yemek-tarifi -p 80:80 ssevginurr/yemek-tarifi:latest
