name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy docker container
        run: |
          docker pull ssevginurr/yemek-tarifi:latest
          docker stop yemek-tarifi || true
          docker rm yemek-tarifi || true
          docker run -d --name yemek-tarifi -p 80:80 ssevginurr/yemek-tarifi:latest
